#!/usr/bin/env python3
"""
Index Accelerator — Sitemap & Re-Crawl Signal Engine
======================================================
Accelerates Google indexing by:
  - Generating updated sitemap with lastmod timestamps
  - Refreshing content modification dates
  - Providing Search Console submission guidance
  - Tracking index velocity over time

For Blogger sites, sitemaps are auto-generated by Blogger at:
  https://babynameideas2026.blogspot.com/sitemap.xml
  https://babynameideas2026.blogspot.com/feeds/posts/default?orderby=updated

This module:
  1. Verifies sitemap accessibility
  2. Lists recently updated posts for re-crawl priority
  3. Generates a re-crawl priority list for Search Console
  4. Tracks index velocity (posts published / indexed over time)
"""

import json
import logging
import os
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("index_accelerator")

BASE_DIR = Path(__file__).resolve().parent
POSTS_DIR = BASE_DIR / "posts"
BLOG_URL = os.environ.get("BLOG_URL", "https://babynameideas2026.blogspot.com")
INDEX_LOG = BASE_DIR / "index_log.json"


def get_recently_modified(days: int = 14) -> list:
    """Get posts modified in the last `days` days. These are re-crawl priority."""
    cutoff = datetime.now() - timedelta(days=days)
    recent = []

    for p in POSTS_DIR.glob("*.md"):
        mtime = datetime.fromtimestamp(p.stat().st_mtime)
        if mtime > cutoff:
            text = p.read_text(encoding="utf-8")
            slug = p.stem
            title = p.stem
            if text.startswith("---"):
                parts = text.split("---", 2)
                if len(parts) >= 3:
                    for line in parts[1].split("\n"):
                        if line.startswith("title:"):
                            title = line.split(":", 1)[1].strip().strip('"').strip("'")
                        elif line.startswith("slug:"):
                            slug = line.split(":", 1)[1].strip().strip('"').strip("'")

            recent.append({
                "slug": slug,
                "title": title,
                "modified": mtime.strftime("%Y-%m-%d %H:%M"),
                "url": f"{BLOG_URL}/{slug}.html",
                "priority": "high" if (datetime.now() - mtime).days <= 3 else "medium",
            })

    recent.sort(key=lambda x: x["modified"], reverse=True)
    return recent


def generate_re_crawl_list(output_path: Optional[Path] = None) -> list:
    """Generate a prioritized re-crawl list for Search Console submission."""
    recent = get_recently_modified(days=30)
    priority_order = []

    for r in recent:
        priority_order.append({
            "url": r["url"],
            "last_modified": r["modified"],
            "priority": "high" if r["priority"] == "high" else "normal",
        })

    if output_path:
        output_path.write_text(json.dumps(priority_order, indent=2))
        log.info("Re-crawl list saved to: %s (%d URLs)", output_path, len(priority_order))

    return priority_order


def get_sitemap_urls() -> dict:
    """Return all relevant sitemap/index URLs for the Blogger site."""
    return {
        "sitemap": f"{BLOG_URL}/sitemap.xml",
        "atom_feed": f"{BLOG_URL}/feeds/posts/default?orderby=updated",
        "rss_feed": f"{BLOG_URL}/feeds/posts/default?alt=rss",
        "search_console_submit": "https://search.google.com/search-console/sitemaps",
    }


def log_index_velocity():
    """Track and log the index velocity (content growth rate)."""
    total_posts = len(list(POSTS_DIR.glob("*.md")))

    prev_total = total_posts
    if INDEX_LOG.exists():
        try:
            data = json.loads(INDEX_LOG.read_text())
            prev_total = data.get("total_posts", total_posts)
        except Exception:
            pass

    velocity = total_posts - prev_total

    log_data = {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "total_posts": total_posts,
        "new_since_last": velocity,
        "timestamps": [],
    }

    # Keep rolling log
    if INDEX_LOG.exists():
        try:
            existing = json.loads(INDEX_LOG.read_text())
            for ts in existing.get("timestamps", [])[-90:]:  # Keep 90 days
                log_data["timestamps"].append(ts)
        except Exception:
            pass

    log_data["timestamps"].append({
        "date": datetime.now().strftime("%Y-%m-%d"),
        "total": total_posts,
    })

    INDEX_LOG.write_text(json.dumps(log_data, indent=2))
    log.info(
        "Index velocity: %d total posts, %+d since last check",
        total_posts, velocity,
    )
    return log_data


def accelerate():
    """Run all index acceleration tasks."""
    print("=" * 60)
    print("INDEX ACCELERATOR")
    print("=" * 60)

    # 1. Sitemaps
    sitemaps = get_sitemap_urls()
    print("\n1. Blogger Sitemaps:")
    for name, url in sitemaps.items():
        print(f"   {name}: {url}")

    # 2. Recently modified posts
    recent = get_recently_modified(days=14)
    print(f"\n2. Recently modified (last 14 days): {len(recent)} posts")
    for r in recent[:5]:
        print(f"   [{r['priority']}] {r['title'][:55]} — modified {r['modified']}")

    # 3. Re-crawl priority
    crawl_list = generate_re_crawl_list()
    high_priority = [u for u in crawl_list if u["priority"] == "high"]
    print(f"\n3. Re-crawl priority: {len(high_priority)} high, {len(crawl_list)} total")

    # 4. Index velocity
    velocity = log_index_velocity()
    print(f"\n4. Index velocity: {velocity['total_posts']} posts ({velocity['new_since_last']:+d} since last)")

    # 5. Guidance
    print("\n5. Next Steps:")
    print("   → Submit sitemap at Google Search Console")
    print("   → Request indexing for high-priority URLs")
    print("   → Monitor index coverage report for errors")

    return {
        "sitemaps": sitemaps,
        "recent_posts": len(recent),
        "high_priority": len(high_priority),
        "total_posts": velocity["total_posts"],
        "velocity": velocity["new_since_last"],
    }


if __name__ == "__main__":
    accelerate()
