"""Execution report generator.

Saves a human-readable report of every pipeline execution to
``logs/reports/``.  Reports are named with the timestamp and article
slug.

Example filename::

    logs/reports/20260710-120000-100-japanese-baby-names.md
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from config.logging import get_logger
from config.settings import AUTOMATION_REPORTS_DIR

log = get_logger(__name__)


class ReportError(Exception):
    """Raised when report generation fails."""


def save_report(
    result: dict[str, Any],
    elapsed_ms: int,
    warnings: list[str] | None = None,
) -> Path:
    """Generate and save an execution report.

    Args:
        result:     The result dict from ``publisher.publish_article()``.
        elapsed_ms: Total execution time in milliseconds.
        warnings:   Any non-fatal warnings encountered.

    Returns:
        Path to the saved report file.

    Raises:
        ReportError: If the report cannot be written.
    """
    now = datetime.utcnow()
    timestamp = now.strftime("%Y%m%d-%H%M%S")
    slug = (result.get("slug") or result.get("title", "unknown"))[:50]
    safe_slug = "".join(c if c.isalnum() or c in "-_" else "_" for c in slug)

    filename = f"{timestamp}-{safe_slug}.md"
    AUTOMATION_REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    report_path = AUTOMATION_REPORTS_DIR / filename

    success = result.get("success", False)

    lines: list[str] = [
        f"# Pipeline Execution Report",
        f"",
        f"- **Timestamp:** {now.isoformat()}",
        f"- **Status:** {'✅ Success' if success else '❌ Failed'}",
        f"- **Elapsed:** {elapsed_ms} ms ({_format_duration(elapsed_ms)})",
        f"",
        f"## Article",
        f"",
        f"- **Title:** {result.get('title', 'N/A')}",
        f"- **Slug:** {result.get('slug', 'N/A')}",
        f"- **Article ID:** {result.get('article_id', 'N/A')}",
        f"",
    ]

    if success:
        lines.extend([
            f"## Published",
            f"",
            f"- **Blogger URL:** {result.get('blogger_url', 'N/A')}",
            f"- **Post ID:** {result.get('blogger_post_id', 'N/A')}",
            f"- **Published At:** {result.get('published_at', 'N/A')}",
            f"- **Labels:** {', '.join(result.get('labels', []))}",
            f"",
        ])

    if result.get("blogger_post_id"):
        lines.extend([
            f"## Image",
            f"",
        ])
        if result.get("blogger_post_id"):
            lines.append(f"- **Provider:** {result.get('provider', 'N/A')}")

    if warnings:
        lines.extend([
            f"## Warnings",
            f"",
        ])
        for w in warnings:
            lines.append(f"- ⚠️  {w}")
        lines.append("")

    if not success:
        lines.extend([
            f"## Error",
            f"",
            f"```",
            f"{result.get('error_message', 'Unknown error')}",
            f"```",
            f"",
        ])

    lines.extend([
        f"---",
        f"",
        f"_Generated by Blogger AI Publisher Pro Automation Engine v1.0_",
        f"",
    ])

    try:
        report_path.write_text("\n".join(lines), encoding="utf-8")
        log.info("Report saved: %s", report_path)
        return report_path
    except OSError as exc:
        raise ReportError(f"Failed to write report: {exc}") from exc


def _format_duration(ms: int) -> str:
    """Format milliseconds into a human-readable duration.

    Args:
        ms: Duration in milliseconds.

    Returns:
        Human-readable string like ``"3.2s"`` or ``"1m 5s"``.
    """
    seconds = ms / 1000
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{minutes}m {secs}s"
